### ISSUE TITLE
About 23 input features based on the results of this correlation study 

### ISSUE THREAD

**Issue by MichaelaQ** [sinansonlu/animation-personality#1]
Hello.Thank you for your amazing work.
I'm interested in your work and I want to know about 23 input features you chose based on the results of this correlation study.I can't find these features in your code.
If possible,could you please tell me more details about these features?

**Comment by sinansonlu** [comment]
Hi, sorry for replying late. Thank you for your interest. We will soon include the full code for the analysis. For now, these are the 23 input features used in the paper:

**joint pair distances:**
1. Hand_L - Hand_R'
2. Foot_L - Foot_R
3. Head - Hand_L
4. Head - Hand_R

**joint speed:**
1. Hand_L
2. Hand_R
3. Foot_L
4. Foot_R

**joint trio angles:**
1. Hips - Spine - Head
2. UpperArm_L - LowerArm_L - Hand_L
3. UpperArm_R - LowerArm_R - Hand_R
4. UpperLeg_R - LowerLeg_R - Foot_R
5. UpperLeg_L - LowerLeg_L - Foot_L
6. Hand_L - Hips - Hand_R
7. LowerArm_L - Hips - LowerArm_R
8. LowerLeg_R - Hips - LowerLeg_L
9. Foot_R - Hips - Foot_L

**joint acceleration:**
1. Hand_L
2. Hand_R
3. LowerArm_L
4. LowerArm_R
5. Foot_R
6. Foot_L

**Comment by MichaelaQ** [comment]
Thank you！
